### ISSUE TITLE
Translation auto-sync issue

### ISSUE THREAD

**Issue by iliakan** [javascript-tutorial/fr-old.javascript.info#12]
I created a script for auto-syncing changed files from English to translated repos.

As of now, it doesn't work with this repository, because it seems you did not fork, but rather created it from the scratch.

So git can't compare unrelated histories and merge changed files.

I'd suggest to re-create this repo: clone it from `en.javascript.info` and then update its content with your currently translated articles. 

This way auto-sync will work now and in the future.

**Comment by HachemiH** [comment]
ok i'll do it, it'll be a good reason to check and fix all previous translated articles.

**Comment by HachemiH** [comment]
Hi,
I've finish to update the content of a fresh cloned "en" version. 
Can you test your auto-sync script on this repo : https://github.com/HachemiH/en.javascript.info

I'll rename it and transfer it if it's ok for you.

**Comment by iliakan** [comment]
I can't test, it needs to be in the org.
Can you transfer it to @iliakan, and I'll make it a new fr.javascript.info, while keeping a backup of the current one?

**Comment by HachemiH** [comment]
Done, and i got a back up of the previous version, you can delete it.

**Comment by iliakan** [comment]
I can't transfer it to the org, because it's a github fork.

I will contact github to unfork it.

The idea was to clone the repo and push, not fork, because github does not allow the fork and the original version to coexist in a single org/user.

**Comment by iliakan** [comment]
I believe tomorrow they'll do that.

**Comment by HachemiH** [comment]
Hum, ok sorry ... My bad

**Comment by iliakan** [comment]
It's easy to unfork, I'll write back when done.

**Comment by iliakan** [comment]
Seems to be working fine now =)

**Comment by iliakan** [comment]
Thanks!

**Comment by HachemiH** [comment]
Good.

The issues are disabled on the new repo ?
Can i have the previous rights on this new repo to continue my translate ?

**Comment by iliakan** [comment]
Enabled issues, sorry. You don't have rights? Should have.

**Comment by HachemiH** [comment]
On this (old) repo you add me on the admin team, but not on the new one.

**Comment by iliakan** [comment]
Changed to admin.

**Comment by HachemiH** [comment]
Thank you.
